import Providers from "@/app/utilities/Providers"
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  weight: ["400", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className={`${inter.className} text-[#1D1F29] dark:text-white dark:bg-[#1D1F29]`}><Providers>{children}</Providers></body>
    </html>
  );
}
